FROM node:alpine

WORKDIR /usr/app

RUN apk add postgresql-client
COPY ./package.json ./
RUN npm install
COPY ./ ./

CMD ["npm", "run", "dev"]

### COMMAND HELPERS
# docker build -t dzheng42/node-boilerplate -f Dockerfile.dev .
# docker run -p 8888:8888 dzheng42/node-boilerplate
# docker attach <container_id>
# docker exec -it <container-id> /bin/bash