version: '3'
services:
  postgres:
    image: 'postgres:10'
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=boilerplate
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis-server:
    image: 'redis:latest'
    ports:
      - "6379:6379"

  node-app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8888:8888"
    volumes:
      - /usr/app/node_modules # Try not to map node_modules
      - .:/usr/app
    environment:
      - NODE_ENV=development
      - POSTGRES_PASSWORD=root
    restart: always
    depends_on:
      - postgres
    command: ./wait-for.sh postgres -- npm run dev

### COMMAND HELPERS
# docker-compose up --build
# docker-compose ps
## Launch in background
# docker-compose up -d
## Kill docker compose services
# docker-compose down